### ISSUE TITLE
"@get('/todo/{id}')" route doesn't seem to work

### ISSUE THREAD

**Issue by paillave** [strongloop/loopback4-example-getting-started#17]
http://localhost:3000/todo is working fine:
`[{"id":1,"title":"Take over the galaxy","desc":"MWAHAHAHAHAHAHAHAHAHAHAHAHAMWAHAHAHAHAHAHAHAHAHAHAHAHA"}]`
but http://localhost:3000/todo/1 returns
`{"statusCode":500}`
on the console, I get this:
`Unhandled error in GET /todo/1: 500 TypeError: Cannot use 'in' operator to search for '$ref' in undefined
    at hasArgumentsFromBody (/home/paillave/Documents/loopback4-example-getting-started/node_modules/@loopback/rest/dist/src/parser.js:59:20)
    at loadRequestBodyIfNeeded (/home/paillave/Documents/loopback4-example-getting-started/node_modules/@loopback/rest/dist/src/parser.js:43:10)
    at DefaultSequence.parseOperationArgs [as parseParams] (/home/paillave/Documents/loopback4-example-getting-started/node_modules/@loopback/rest/dist/src/parser.js:38:24)
    at DefaultSequence.handle (/home/paillave/Documents/loopback4-example-getting-started/node_modules/@loopback/rest/dist/src/sequence.js:84:37)
    at HttpHandler._handleRequest (/home/paillave/Documents/loopback4-example-getting-started/node_modules/@loopback/rest/dist/src/http-handler.js:32:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)`

I may ask a stupid question, but as I'm trying to learn the technology, I'm looking for a fully working simple application that I can blindly rely on to understand how LB4 works.
(another question: on LB3, the swagger was implement out of the box by default, but here, there is nothing. Is it normal?)

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-next/pull/814. Please run `npm i` and try again.

**Comment by paillave** [comment]
thanks!!!
any advice to get the swagger working? I was so easy on version 3!

**Comment by raymondfeng** [comment]
Try http://localhost:3000/swagger-ui. At the moment, we use a hosted web UI for the explorer and a bundled version will be added later.
